#!/bin/sh

set -e

WINE_NAME="${WINE_NAME:-docker-wine}"
WINE_ENV_VOLUME="${WINE_ENV_VOLUME:-$HOME/.wine_env/$WINE_NAME}"

[ -d "$WINE_ENV_VOLUME" ] || mkdir -p "$WINE_ENV_VOLUME"

docker run -it --rm \
    --name="$WINE_NAME" \
    --hostname="$(hostname)" \
    --shm-size="1g" \
    --env="USER_NAME=$(id -un)" \
    --env="USER_GROUP=$(id -gn)" \
    --env="USER_UID=$(id -u)" \
    --env="USER_GID=$(id -g)" \
    --env="USER_HOME=$HOME" \
    --workdir="$HOME" \
    --volume="/etc/localtime:/etc/localtime:ro" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:ro" \
    --env="DISPLAY" \
    --volume="$HOME/.Xauthority:/tmp/.Xauthority:ro" \
    --env="XAUTHORITY=/tmp/.Xauthority" \
    --device="/dev/dri" \
    --volume="/run/user/$(id -u)/pulse/native:/tmp/pulse.sock" \
    --env="PULSE_SERVER=unix:/tmp/pulse.sock" \
    --volume="$HOME/.config/pulse/cookie:/tmp/pulse.cookie:ro" \
    --env="PULSE_COOKIE=/tmp/pulse.cookie" \
    --env="WINEDEBUG=-all" \
    --env="WINEARCH=win32" \
    --env="WINEPREFIX=$HOME/.wine" \
    --env="DXVK_FRAME_RATE=60" \
    --volume="$WINE_ENV_VOLUME:$HOME" \
    docker-wine:bullseye "$@"
