#!/bin/sh

set -e

CONTAINER_CLI="$(which podman || :)"
[ -z "$CONTAINER_CLI" ] && CONTAINER_CLI="$(which docker || :)"
if [ -z "$CONTAINER_CLI" ]; then
    echo 'ERROR: podman and docker not found' >&2
    exit 1
fi

CONTAINER_ARGS=""
while [ -n "$1" ]; do
    if echo "$1" | grep -q -E '^-'; then
        CONTAINER_ARGS="$CONTAINER_ARGS $1"
        shift
    else
        break
    fi
done

WINE_NAME="${WINE_NAME:-wine-default}"
WINE_IMAGE="${WINE_IMAGE:-wine:latest}"
WINE_ENV_VOLUME="${WINE_ENV_VOLUME:-$HOME/.wine_env/$WINE_NAME}"

"$CONTAINER_CLI" run -it --rm \
    --name="$WINE_NAME" \
    --hostname="$(hostname)" \
    --shm-size="1g" \
    --volume="/etc/localtime:/etc/localtime:ro" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:ro" \
    --env="DISPLAY" \
    --volume="${XAUTHORITY:-$HOME/.Xauthority}:/tmp/.Xauthority:ro" \
    --env="XAUTHORITY=/tmp/.Xauthority" \
    --device="/dev/dri" \
    --volume="/run/user/$(id -u)/pulse/native:/tmp/pulse.sock:ro" \
    --env="PULSE_SERVER=unix:/tmp/pulse.sock" \
    --volume="${PULSE_COOKIE:-$HOME/.config/pulse/cookie}:/tmp/pulse.cookie:ro" \
    --env="PULSE_COOKIE=/tmp/pulse.cookie" \
    --device="/dev/input" \
    --volume="$WINE_ENV_VOLUME:/data" \
    --env="HOME=/data" \
    --workdir="/data" \
    --env="WINEPREFIX=/data/.wine" \
    --env="WINEDEBUG=fixme-all" \
    --env="DXVK_LOG_PATH=none" \
    --env="DXVK_FRAME_RATE=60" \
    --env="DXVK_HUD=compiler" \
    $CONTAINER_ARGS \
    "$WINE_IMAGE" "$@"
